version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 8011:5432
    environment:
      - POSTGRES_DB=fdl

  api:
    image: fdl-mc/api/users
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8010:8000
    depends_on:
      - db
